version: 2.1

commands:
  setup_credential:
    steps:
      - run:
          name: Setup Credential
          command: |
            mkdir -p /etc/google/
            echo "${CI_GOOGLE_SERVICE_KEY_BASE64}" | base64 --decode --ignore-garbage > "${GOOGLE_APPLICATION_CREDENTIALS}"

  make_dataset:
    steps:
      - run:
          name: Authorization
          command: gcloud auth activate-service-account --key-file ${GOOGLE_APPLICATION_CREDENTIALS}
      - run:
          name: bqls
          command: bq ls
      - run:
          name: circlesha1
          command: echo "${CIRCLE_SHA1:0:7}"
      - run:
          name: datasetname
          command: date "+%Y%m%d"
      - run:
          name: datasetname2
          command: echo "export BQDATASET=${BQ_DATASET_PREFIX}-`date '+%Y%m%d'`-${CIRCLE_SHA1:0:7}" >> $BASH_ENV
      - run:
          name: echo datasetname
          command: echo "${BQDATASET}"

executors:
  gcloud:
    docker:
      - image: google/cloud-sdk:latest
        environment:
          GOOGLE_APPLICATION_CREDENTIALS: /etc/google/application_default_credentials.json

jobs:
  build:
    executor: gcloud
    steps:
      - checkout
      - setup_credential
      - make_dataset

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
