version: 2.1

commands:
  setup_credential:
    steps:
      - run:
          name: Setup Credential
          command: |
            mkdir -p /etc/google/
            echo "${CI_GOOGLE_SERVICE_KEY_BASE64}" | base64 --decode --ignore-garbage > "${GOOGLE_APPLICATION_CREDENTIALS}"

  make_dataset:
    steps:
      - run:
          name: Authorization
          command: gcloud auth activate-service-account --key-file ${GOOGLE_APPLICATION_CREDENTIALS}
      - run:
          name: set env BQ_DATASET
          command: echo "export BQ_DATASET=${BQ_DATASET_PREFIX}_`date '+%Y%m%d'`_${CIRCLE_SHA1:0:7}" >> $BASH_ENV
      - run:
          name: echo datasetname
          command: echo "${BQ_DATASET}"
      - run:
          name: make dataset
          command: bq --location=US mk --dataset $GCP_PROJECT:$BQ_DATASET
      - run:
          name: delete dataset
          command: bq rm -r -f --dataset $GCP_PROJECT:$BQ_DATASET

executors:
  gcloud:
    docker:
      - image: google/cloud-sdk:latest
        environment:
          GOOGLE_APPLICATION_CREDENTIALS: /etc/google/application_default_credentials.json

jobs:
  build:
    executor: gcloud
    steps:
      - checkout
      - setup_credential
      - make_dataset

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
