#!/bin/bash -eu

bq --location=US mk --dataset $GCP_PROJECT:$BQ_DATASET

bq mk \
--table \
$GCP_PROJECT:$BQ_DATASET.test \
string_column:STRING,integer_column:INTEGER,date_column:DATE,timestamp_column:TIMESTAMP
